
package com.test.cxf.generate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://service.cxf.test.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "Integer", targetNamespace = "")
    @RequestWrapper(localName = "getUserName", targetNamespace = "http://service.cxf.test.com/", className = "com.test.cxf.generate.GetUserName")
    @ResponseWrapper(localName = "getUserNameResponse", targetNamespace = "http://service.cxf.test.com/", className = "com.test.cxf.generate.GetUserNameResponse")
    public String getUserName(
            @WebParam(name = "userId", targetNamespace = "")
                    Integer userId);

    /**
     * 
     * @param userId
     * @return
     *     returns com.test.cxf.generate.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://service.cxf.test.com/", className = "com.test.cxf.generate.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://service.cxf.test.com/", className = "com.test.cxf.generate.GetUserResponse")
    public User getUser(
            @WebParam(name = "userId", targetNamespace = "")
                    Integer userId);

}
